name: DEV - Deploy Identity Providers to Keycloak Infrastructure As Code
on:
  workflow_dispatch:
jobs:
  keycloak-infrastructure-as-code:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: check out repository
        uses: actions/checkout@v5
      - name: run script
        uses: actions/github-script@v8
        env:
          KC_REALM_ID: "${{ secrets.KC_REALM_ID }}"
          KC_ENVIRONMENT: "dev"
          KC_CLIENT_ID: ${{ secrets.KC_CLIENT_ID }}
          KC_CLIENT_SECRET: ${{ secrets.KC_CLIENT_SECRET }}
          KC_BASIC_BCEID_CLIENT_ID: ${{ secrets.KC_BASIC_BCEID_CLIENT_ID }}
          KC_BASIC_BCEID_SECRET: ${{ secrets.KC_BASIC_BCEID_SECRET }}
          KC_BCSC_CLIENT_ID: ${{ secrets.KC_BCSC_CLIENT_ID }}
          KC_BCSC_SECRET: ${{ secrets.KC_BCSC_SECRET }}
          KC_IDIR_CLIENT_ID: ${{ secrets.KC_IDIR_CLIENT_ID }}
          KC_IDIR_SECRET: ${{ secrets.KC_IDIR_SECRET }}

        with:
          script: |
            require('./keycloak/tools/infrastructure-as-code/identity-provider/script.js');

      - run: echo "üçè This job's status is ${{ job.status }}."
